name: build-back
on:
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  build-back:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Rename .env.test
        run: cp .env.test .env

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn build
